import type { Metadata } from "next";
import { Geist_Mono, Inter, STIX_Two_Text } from "next/font/google";
import "./globals.css";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const stix = STIX_Two_Text({
  variable: "--font-stix",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${stix.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col scroll-smooth`}
      >
        <Header />
        <main className="flex-1 pt-[80px] md:pt-[96px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
